[llm]
model = "gpt-4.5-turbo"
temperature = 0.3

[web]
surf_timeout_seconds = 15
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"