[llm]
model = "gpt-4-turbo-preview"
temperature = 0.5
# Costs info: https://openai.com/pricing#language-models
input_costs_per_mill = 10   # dollars
output_costs_per_mill = 30  # dollars

[embeddings]
model = "text-embedding-3-small"
cost_per_mill = 0.02  # dollars

[tts]
model = "tts-1"
voice = "shimmer"
cost_per_mill = 15 # dollars

[web]
surf_timeout_seconds = 15
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"

[search]
past_days = 1
blacklist = ['wikipedia.org', 'medium.com']
# Google Cloud pricing
cost_per_query = 0.005  # dollars

[editorial]
name = "Tech by AI"
reporters = 2
reporter_items = 5
final_items = 7
max_words_per_item = 150
subject = "tech and AI"
topics = [
        "Foundation Models", 
        "Uses of Generative AI", 
        "AI Regulation and Policy", 
        "AI and Cybersecurity", 
        "AI in Robotics",
        "Humanoid Robots",
        "Promising startups in Generative AI", 
        "Hardware for AI",
        "New Generative AI models",
        "Cutting-edge capabilities and breakthoughs in AI",
        "New AI-related researches"
        ]
companies = [
        "OpenAI", 
        "Anthropic", 
        "Mistral", 
        "Google", 
        "Meta", 
        "Cohere", 
        "Microsoft", 
        "Amazon",
        "NVidia", 
        "Midjourney", 
        "Stability AI", 
        "Eleven Labs", 
        "Hugging Face"
        ]
people = [
        "Aravind Srinivas", 
        "Brett Adcock", 
        "Satya Nadella",
        "Yam Peleg", 
        "Guillaume Lample", 
        "Arthur Mensch", 
        "Yann LeCun", 
        "Andrej Karpathy", 
        "Andrew Ng", 
        "Geoffrey Hinton"
        ]