name: Daily Publication

on:
  workflow_dispatch: 
  schedule:
    - cron:  '0 3 * * *'  

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg libavcodec-extra
        python -m pip install --upgrade pip
        pip install -e .  
    
    - name: Run 
      run: run_routine
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GOOGLE_SEARCH_CSE_ID: ${{ secrets.GOOGLE_SEARCH_CSE_ID }}
        GOOGLE_SEARCH_API_KEY: ${{ secrets.GOOGLE_SEARCH_API_KEY }}
    
    - name: Commit Changes
      run: |
        git config --global user.name ${{ secrets.USERNAME }}
        git config --global user.email ${{ secrets.EMAIL_ADDRESS }}
        git add .
        CURRENT_TIME=$(date +'%Y-%m-%d %H:%M:%S')
        git commit -m "Automated publication: $CURRENT_TIME" || echo "No changes to commit"
        git push
