name: Daily Publication

on:
  schedule:
    - cron:  '0 3 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .  
    
    - name: Run 
      run: run_routine
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GOOGLE_SEARCH_CSE_ID: ${{ secrets.GOOGLE_SEARCH_CSE_ID }}
        GOOGLE_SEARCH_API_KEY: ${{ secrets.GOOGLE_SEARCH_API_KEY }}
    
    - name: Commit Changes
      run: |
        git config --global user.name 'Shaked Zychlinski'
        git config --global user.email ${{ secrets.EMAIL_ADDRESS }}
        git add .
        git commit -m "Automated update: $CURRENT_TIME" || echo "No changes to commit"
        git push
