name: Test X

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg libavcodec-extra xvfb
        python -m pip install --upgrade pip
        pip install -e .  
    
    - name: Run Test
      run: python test.py
  